    </td>
  </tr>
</table>
<br>
<hr><table width="100%"><tr><td valign="top" align="right" width="100%"><a href="rss.php"><img src="rss.gif" border="0"><img src="xml.gif" border="0"></a></td></tr></table>
<h6>Website &copy; 2005 Kim Possible Fanfiction; Kim Possible characters &copy; 2002-2005 <a href="http://www.disney.com">Disney</a><br>Copyright on the actual material is held by the author. Contact them for permission to distribute.<br>Coded by <a href="http://www.thescripters.com" target="_blank">TheScripters.com</a>; All rights reserved.</h6>
</body>
</html>
