<h2>Ratings Guide</h2>
<center>
<img src="ratingsimages/guide.jpg"><br>
<br>
<img src="ratingsimages/k.jpg"><br>
<br>
<img src="ratingsimages/kplus.jpg"><br>
<br>
<img src="ratingsimages/t.jpg"><br>
<br>
<img src="ratingsimages/m.jpg"><br>
<br>
<img src="ratingsimages/ma.jpg"><br>
<br>
<font size=5>Ratings guide courtesy <a href="http://www.fictionratings.com/" target="_blank">FictionRatings.com</a>.</font>
</center>


