<h2>Register</h2><br>
<script src="includes/reg.js"></script>
<form action="register.php" name="RegisterForm" method="post">
<center>
<table>
  <tr>
    <td align="right"><b>Name:</b></td>
    <td><input type="text" name="Name" maxlength="40"></td>
  </tr>
  <tr>
    <td align="right"><b>Email:</b></td>
    <td><input type="text" name="Email" maxlength="40"></td>
  </tr>
  <tr>
    <td align="right"><b>Password:</b></td>
    <td><input type="password" name="Password" maxlength="25"></td>
  </tr>
  <tr>
    <td align="right"><b>Re-type Password:</b></td>
    <td><input type="password" name="Password1" maxlength="25"></td>
  </tr>
  <tr>
    <td colspan="2" align="center"><input type="submit" value="Register!"></td>
  </tr>
</table>
</center>
</form>
