<!doctype html public "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Kim Possible Fanfiction Megasite || Editor's Panel</title>
<meta name="resource-type" content="document">
<meta name="revisit-after" content="5">
<meta name="classification" content="Entertainment">
<meta name="description" content="Website for fanfiction for the Disney Channel series Kim Possible. Free submission.">
<meta name="keywords" content="Kim Possible, KP, Ron Stoppable, Rufus, Disney, Drakken, Shego">
<meta name="robots" content="ALL">
<meta name="distribution" content="Global">
<meta name="rating" content="General">
<meta name="copyright" content="© 2005-2006 KPFanfiction.com; coded by TheScripters.com">
<meta name="author" content="TheScripters">
<meta http-equiv="reply-to" content="webmaster@kpfanfiction.com">
<meta http-equiv="Content-Language" content="en-us">
<link rel="meta" href="http://www.kpfanfiction.com/labels.rdf" type="application/rdf+xml" title="ICRA labels" />
<link title="RSS" rel="alternate" type="application/rss+xml" href="http://www.kpfanfiction.com/rss.php">
<link rel="stylesheet" href="includes/kpff.css" type="text/css">
</head>

<body>
<h1>Kim Possible Fanfiction</h1><br><br>
<table width="100%">
  <tr>
    <td valign="top" width="150"><h3>Menu:</h3>
    <center><a href="http://www.kpfanfiction.com" target="_blank" onmouseover="window.status='KPFF Main';return true" onmouseout="window.status='';return true">KPFF Main</a></center>
      <ul>
      <li><a href="index.php" onmouseover="window.status='';return true">Main</a></li>
      <li><a href="verify.php?p=list" onmouseover="window.status='';return true"><nobr>Inactive Fics</nobr></a></li>
      <li><a href="index.php?mode=editmain" onmouseover="window.status='';return true"><nobr>Update Index</nobr></a></li>
      <li><a href="index.php?mode=editidx" onmouseover="window.status='';return true"><nobr>Editor's Index</nobr></a></li>
      <li><a href="index.php?mode=pick" onmouseover="window.status='';return true">Editor's Pick</a></li>
      <li><a href="index.php?mode=rate" onmouseover="window.status='';return true"><nobr>Fic Ratings</nobr></a></li>
      <li><a href="index.php?mode=ficedit" onmouseover="windowstatus='';return true">Fic Info</a></li>
      <li><a href="index.php?mode=rules" onmouseover="window.status='';return true">Rules Config</a></li>
      <li><a href="index.php?mode=authors" onmouseover="window.status='';return true">Author List</a></li>
      <li><a href="index.php?mode=rss" onmouseover="window.status='';return true">RSS Config</a></li>
      <li><a href="index.php?mode=mail" onmouseover="window.status='';return true">Email Authors</a></li>
      <li><a href="index.php?mode=msgbrd" onmouseover="window.status='';return true">Message Area</a></li>
      <li><a href="phpinfo.php" target="_blank" onmouseover="window.status='';return true">PHP Info</a></li>
      <li><a href="index.php?mode=contact" onmouseover="window.status='';return true"><nobr>Contact TheScripters</nobr></a></li>
      </ul>
    </td>
    <td>
